### PR TITLE
Fission Reactor Safety by ExplodeyWolf

### PR DESCRIPTION
**Pull request by atlgeek007**
submitted to me by ExplodeyWolf on the Discord since they're not familiar with Git/etc.

### CODE REVIEW

**Review by NielsPilgaard — APPROVED** [review]

**Comment by NielsPilgaard** [comment]
Thank you kindly, both of you :D

**Comment by atlgeek007** [comment]
I don't actually know if a new page will auto generate or if something has to be done on the gitbook side, it's still not showing there but my powah edit is.

Thanks for the merge though :)

**Comment by peanut707** [comment]
Thanks for the merge 😀

**Comment by NielsPilgaard** [comment]
Found it! It needed to be added to the summary as well :)
https://github.com/EnigmaticaModpacks/Docs-Enigmatica6/commit/65fd169af9e48a2c7c8d0006284df2ef26b91e35

**Pull request merged**
